# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - bugfix/*
      - hotfix/*
    exclude:
      - development
      - feature/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: PowerShell@2
    displayName: 'NUKE Compile'
    inputs:
      filePath: 'build.ps1'
      arguments: '--configuration $(BuildConfiguration) -target Compile --output $(Build.ArtifactStagingDirectory)'